option(ASTER_ENABLE_CUDA "Build CUDA backend" OFF)
option(ASTER_ENABLE_CUDF "Use libcudf operators" OFF)
option(ASTER_ENABLE_NVRTC "Enable NVRTC pipeline fusion" OFF)
option(ASTER_ENABLE_CUFILE "Enable GPUDirect Storage (cuFile)" OFF)
option(ASTER_ENABLE_NCCL "Enable NCCL multi GPU exchange" OFF)
option(ASTER_ENABLE_UCX "Enable UCX cross node exchange" OFF)
option(ASTER_ENABLE_NVCOMP "Enable nvCOMP general purpose decode" OFF)
option(ASTER_ENABLE_ARROW "Enable Arrow/Parquet bridge" OFF)
option(ASTER_ENABLE_SUBSTRAIT "Enable Substrait protobuf consumer" OFF)
option(ASTER_ENABLE_DUCKDB "Build DuckDB extension" OFF)
option(ASTER_ENABLE_LZ4 "Enable LZ4 outer compression" OFF)
option(ASTER_ENABLE_ZSTD "Enable Zstd outer compression" OFF)
option(ASTER_ENABLE_CUVS "Enable cuVS vector index operators" OFF)
option(ASTER_BUILD_TESTS "Build unit tests" ON)
set(ASTER_CUDA_ARCHS "80;90" CACHE STRING "CUDA architectures")

set(ASTER_DEFINITIONS "")
foreach(opt CUDA CUDF NVRTC CUFILE NCCL UCX NVCOMP ARROW SUBSTRAIT DUCKDB LZ4 ZSTD CUVS)
  if(ASTER_ENABLE_${opt})
    list(APPEND ASTER_DEFINITIONS ASTER_HAVE_${opt}=1)
  endif()
endforeach()
