find_package(Threads REQUIRED)
set(ASTER_LINK_LIBS "")
set(ASTER_CUDA_LIBS "")

if(ASTER_ENABLE_CUDA)
  find_package(CUDAToolkit REQUIRED)
  list(APPEND ASTER_LINK_LIBS CUDA::cudart CUDA::cuda_driver)
  if(ASTER_ENABLE_NVRTC)
    list(APPEND ASTER_LINK_LIBS CUDA::nvrtc)
  endif()
  if(ASTER_ENABLE_CUFILE)
    find_library(CUFILE_LIB cufile HINTS ${CUDAToolkit_LIBRARY_DIR} REQUIRED)
    list(APPEND ASTER_LINK_LIBS ${CUFILE_LIB})
  endif()
  if(ASTER_ENABLE_CUDF)
    find_package(cudf REQUIRED)
    find_package(rmm REQUIRED)
    list(APPEND ASTER_LINK_LIBS cudf::cudf rmm::rmm)
  endif()
  if(ASTER_ENABLE_NCCL)
    find_library(NCCL_LIB nccl REQUIRED)
    list(APPEND ASTER_LINK_LIBS ${NCCL_LIB})
  endif()
  if(ASTER_ENABLE_NVCOMP)
    find_package(nvcomp REQUIRED)
    list(APPEND ASTER_LINK_LIBS nvcomp::nvcomp)
  endif()
  if(ASTER_ENABLE_CUVS)
    find_package(cuvs REQUIRED)
    list(APPEND ASTER_LINK_LIBS cuvs::cuvs)
  endif()
endif()

if(ASTER_ENABLE_UCX)
  find_package(ucx REQUIRED)
  list(APPEND ASTER_LINK_LIBS ucx::ucp ucx::ucs)
endif()
if(ASTER_ENABLE_ARROW)
  find_package(Arrow REQUIRED)
  find_package(Parquet REQUIRED)
  list(APPEND ASTER_LINK_LIBS Arrow::arrow_shared Parquet::parquet_shared)
endif()
if(ASTER_ENABLE_SUBSTRAIT)
  find_package(Protobuf REQUIRED)
  list(APPEND ASTER_LINK_LIBS protobuf::libprotobuf substrait::substrait)
endif()
if(ASTER_ENABLE_LZ4)
  find_package(lz4 REQUIRED)
  list(APPEND ASTER_LINK_LIBS lz4::lz4)
endif()
if(ASTER_ENABLE_ZSTD)
  find_package(zstd REQUIRED)
  list(APPEND ASTER_LINK_LIBS zstd::libzstd_shared)
endif()
